spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: empleado-service
          uri: lb://empleado-service
          predicates:
            - Path=/empleados/**
        - id: upload-service
          uri: lb://upload-service
          predicates:
            - Path=/upload/**
        - id: eureka-server
          uri: lb://eureka-server
          predicates:
            - Path=/eureka/**
server:
    port: 8080
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}